# Generated by Django 4.2.7 on 2025-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_designation_slug_alter_specialization_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(),
        ),
    ]
